name: Update monitoring items

on:
  schedule:
    - cron:  '30 9 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install mojimoji
        pip install beautifulsoup4
        pip install requests
        pip install xlrd
        pip install openpyxl
    - name: Run script
      env:
        TZ: Asia/Tokyo
      run: |
        cd tool
        python scraping_monitoring_items.py
        cd ..
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "[Bot] Update monitoring items"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
