name: Update positive_rate.json

on:
  schedule:
    - cron: '10 13 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
    - name: Run script
      env:
        TZ: Asia/Tokyo
        NAME: Terachan0117
        EMAIL: contact@tera-chan.com
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        git config user.name ${NAME}
        git config user.email ${EMAIL}
        git remote set-url origin https://${NAME}:${PASSWORD}@github.com/${NAME}/covid19-toyama
        git checkout development
        cd tool
        python3 positive_rate.py
        cd ..
        git add .
        git commit -m "[Bot] GitHub Actions - auto run (positive_rate.py)"
        git push origin development
